name: CI
on: [push, pull_request]

jobs:
  ubuntu:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: cache-vulkansdk
      id: cache-vulkansdk
      uses: actions/cache@v1
      with:
        path: "1.2.162.1"
        key: vulkansdk-linux-x86_64-1.2.162.1
    - name: vulkansdk
      if: steps.cache-vulkansdk.outputs.cache-hit != 'true'
      run: |
        wget https://sdk.lunarg.com/sdk/download/1.2.162.1/linux/vulkansdk-linux-x86_64-1.2.162.1.tar.gz?Human=true -O vulkansdk-linux-x86_64-1.2.162.1.tar.gz
        tar -xf vulkansdk-linux-x86_64-1.2.162.1.tar.gz
        rm -rf 1.2.162.1/source 1.2.162.1/samples
        find 1.2.162.1 -type f | grep -v -E 'vulkan|glslang' | xargs rm
    - name: build
      run: |
        export VULKAN_SDK=`pwd`/1.2.162.1/x86_64
        mkdir build && cd build
        cmake ../src
        cmake --build . -j 2